spring.application.name=Notification Platform

# DB Creds
spring.datasource.url=jdbc:postgresql://localhost:5432/np_db_local
spring.datasource.username=postgres
spring.datasource.password=PgSup13!

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
